### ISSUE TITLE
Gradle-build error while try-android

### ISSUE THREAD

**Issue by prango71** [mrousavy/Colorwaver#5]
![image](https://user-images.githubusercontent.com/78131793/133881784-bd373293-8208-4ff2-bfe6-e032056d4a5d.png)
When I run react-native run-android this error pops up. My phone is connected through adb.

This is an amazing app and I would love to try it. Plz help me.

**Comment by aliraza-noon** [comment]
@prango71  you are trying to build a release variant I think you don't signing config for that is why it is failing
